# Generated by Django 3.0.9 on 2020-08-03 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='guidancephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='id_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
